services:
  database:
    image: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=$DATABASE_ROOT_PASSWORD
      - MYSQL_DATABASE=$DATABASE_NAME
    ports:
      - $DATABASE_LOCAL_PORT:$DATABASE_DOCKER_PORT
    volumes:
      - data-volume:/data/db

  backend:
    build:
      context: ./backend
    ports:
      - $BACKEND_LOCAL_PORT:$BACKEND_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://database:$DATABASE_DOCKER_PORT/eshop_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC",
        "spring.datasource.username" : "$DATABASE_USER",
        "spring.datasource.password" : "$DATABASE_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
        "spring.jpa.generate-ddl" : "false",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "spring.jpa.properties.hibernate.jdbc.time_zone" : "UTC",
        "server.address" : "0.0.0.0",
        "server.port" : "8080"
        }'
      DATABASE_DOCKER_HOST: database
      DATABASE_DOCKER_PORT: $DATABASE_DOCKER_PORT
    depends_on:
      - database

  frontend:
    build: ./frontend
    ports:
      - $FRONTEND_LOCAL_PORT:80
    depends_on:
      - backend

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8081:8080

volumes:
  data-volume:

# TODO: parent pom.xml
# TODO: Angular Material
# TODO: Swagger UI for backend
